### ISSUE TITLE
Number of SNPs

### ISSUE THREAD

**Issue by moorembioinfo** [zhaoxiaofei/bindash#5]
Hi! 

Is it possible to output number of SNPs in addition to SNP distance. The SNP distance is accurate to those I've checked but I'd be interested in pulling number of SNPs from bindash comparisons. That way if I wanted to know which sketches are within 1000 SNPs of each other or something I could. (or the number of different sites and number of same sites that the SNP distance measure is based on)

Best, 

Matt

**Comment by moorembioinfo** [comment]
Have I understood the 'mutation distance' correctly in the first place? Is this actually mash distance? It doesn't line up exactly with SNP distance

**Comment by zhaoxiaofei** [comment]
Sorry for the extremely late reply. Yes, the mutation distance is a mash distance, the estimated mutation rate. Yes, it doesn't line up with SNP distance. However, from the percentage of k-mers that are shared between two genomes, we can get a rought estimate of the sequence similarity between the two genomes (which is negative correlated with the mutation distance), which can be converted to SNP distance.
