### ISSUE TITLE
cannot compile on M1 MacBook Pro

### ISSUE THREAD

**Issue by jianshu93** [zhaoxiaofei/bindash#8]
Hello Xiaofei,

I have this error when compiling on my M1 MacBook Pro ():

cmake:

-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jianshuzhao/Github/bindash/release

make:

[ 50%] Building CXX object CMakeFiles/bindash.dir/src/bindash.cpp.o
/Users/jianshuzhao/Github/bindash/src/bindash.cpp: In function 'void cmddist(bool, bool, const std::vector<Entity>&, const std::vector<Entity>&, const Sketchargs&, const Distargs&)':
/Users/jianshuzhao/Github/bindash/src/bindash.cpp:361:63: error: aggregate 'std::array<std::priority_queue<std::tuple<double, double, long unsigned int, long unsigned int, long unsigned int, long unsigned int> >, 2048> tophits_arr' has incomplete type and cannot be defined
  361 |                 std::array<std::priority_queue<hit_t>, ISIZE> tophits_arr;
      |                                                               ^~~~~~~~~~~
make[2]: *** [CMakeFiles/bindash.dir/src/bindash.cpp.o] Error 1
make[1]: *** [CMakeFiles/bindash.dir/all] Error 2
make: *** [all] Error 2

It seems the same error on intel MacBook Pro. I have no problems on linux

Thanks,

Jianshu

**Comment by zhaoxiaofei** [comment]
I do not have a Mac now so that I cannot reproduce your error. My best guess is that the declaration of tophits_arr is forbidden by the C++ standard that your compiler is supporting.

There should be a Makefile in /Users/jianshuzhao/Github/bindash/release
Can you modify the CFLAG and CXXFLAG to include "-std=c++11" or "-std=c++17" and see the results?

**Comment by jianshu93** [comment]
Hello Xiaofei, 

I modified to -std=c++17 in the CMakelists.txt in line 4, but I still have the exact error on MacOS: 

-- The C compiler identification is GNU 13.1.0
-- The CXX compiler identification is GNU 13.1.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (0.9s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/jianshuzhao/Github/bindash/build
Jianshus-MBP-2:build jianshuzhao$ ls
CMakeCache.txt      CMakeFiles          Makefile            cmake_install.cmake
Jianshus-MBP-2:build jianshuzhao$ make -j 4
[ 50%] Building CXX object CMakeFiles/bindash.dir/src/bindash.cpp.o
/Users/jianshuzhao/Github/bindash/src/bindash.cpp: In function 'void cmddist(bool, bool, const std::vector<Entity>&, const std::vector<Entity>&, const Sketchargs&, const Distargs&)':
/Users/jianshuzhao/Github/bindash/src/bindash.cpp:361:63: error: aggregate 'std::array<std::priority_queue<std::tuple<double, double, long unsigned int, long unsigned int, long unsigned int, long unsigned int> >, 2048> tophits_arr' has incomplete type and cannot be defined
  361 |                 std::array<std::priority_queue<hit_t>, ISIZE> tophits_arr;
      |                                                               ^~~~~~~~~~~
make[2]: *** [CMakeFiles/bindash.dir/src/bindash.cpp.o] Error 1
make[1]: *** [CMakeFiles/bindash.dir/all] Error 2
make: *** [all] Error 2


Thanks,

Jianshu

**Comment by zhaoxiaofei** [comment]
It looks like the issue is caused by the omission of "#include<tuple>" 
Can you try compiling the code at https://github.com/zhaoxiaofei/bindash/tree/003237acad7d8ab86d97b10051ab227d0f1f6bd9
?

**Comment by jianshu93** [comment]
It seems the problem exists. No worries. I just want to also run it on my laptop. It does work on Linux server. No affect on the actual using.


Thanks for the help.

Jianshu

**Comment by jianshu93** [comment]
Hello Xiaofei,

It turns out that if I use clang (clang++ for g++) compiler on MacOS (intel or M1), everything seems fine with some warnings (sysem default clang will not work but must be the brew install clang). see below:

-- The CXX compiler identification is Clang 16.0.4
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/homebrew/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (2.0s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/jianshuzhao/Github/bindash/build
MacBook-Air:build jianshuzhao$ ls
CMakeCache.txt      CMakeFiles          Makefile            cmake_install.cmake
MacBook-Air:build jianshuzhao$ make -j 4
[ 50%] Building CXX object CMakeFiles/bindash.dir/src/bindash.cpp.o
In file included from /Users/jianshuzhao/Github/bindash/src/bindash.cpp:21:
/Users/jianshuzhao/Github/bindash/src/hashutils.hpp:120:12: warning: array subscript is of type 'char' [-Wchar-subscripts]
                NUC_TO_ID['A'] = NUC_TO_ID['a'] = 1;
                         ^~~~
/Users/jianshuzhao/Github/bindash/src/hashutils.hpp:120:29: warning: array subscript is of type 'char' [-Wchar-subscripts]
                NUC_TO_ID['A'] = NUC_TO_ID['a'] = 1;
                                          ^~~~
/Users/jianshuzhao/Github/bindash/src/hashutils.hpp:121:12: warning: array subscript is of type 'char' [-Wchar-subscripts]
                NUC_TO_ID['C'] = NUC_TO_ID['c'] = 2;
                         ^~~~
/Users/jianshuzhao/Github/bindash/src/hashutils.hpp:121:29: warning: array subscript is of type 'char' [-Wchar-subscripts]
                NUC_TO_ID['C'] = NUC_TO_ID['c'] = 2;
                                          ^~~~
/Users/jianshuzhao/Github/bindash/src/hashutils.hpp:122:12: warning: array subscript is of type 'char' [-Wchar-subscripts]
                NUC_TO_ID['G'] = NUC_TO_ID['g'] = 3;
                         ^~~~
/Users/jianshuzhao/Github/bindash/src/hashutils.hpp:122:29: warning: array subscript is of type 'char' [-Wchar-subscripts]
                NUC_TO_ID['G'] = NUC_TO_ID['g'] = 3;
                                          ^~~~
/Users/jianshuzhao/Github/bindash/src/hashutils.hpp:123:12: warning: array subscript is of type 'char' [-Wchar-subscripts]
                NUC_TO_ID['T'] = NUC_TO_ID['t'] = 4;
                         ^~~~
/Users/jianshuzhao/Github/bindash/src/hashutils.hpp:123:29: warning: array subscript is of type 'char' [-Wchar-subscripts]
                NUC_TO_ID['T'] = NUC_TO_ID['t'] = 4;
                                          ^~~~
8 warnings generated.
[100%] Linking CXX executable bindash
[100%] Built target bindash




and the clang libomp is linked, instead of the gcc libomp:

MacBook-Air:build jianshuzhao$ otool -L /Users/jianshuzhao/bin/bindash
/Users/jianshuzhao/bin/bindash:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/opt/homebrew/opt/llvm/lib/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1500.65.0)

I attached the binary here on aarch64/arm64 on MacOS (need to install llvm and via home-brew)
[bindash.zip](https://github.com/zhaoxiaofei/bindash/files/11691900/bindash.zip)



Thanks,

Jianshu

**Comment by jianshu93** [comment]
I observed performance degradation for clang compile libomp:

Jianshus-MBP-2:NCBI_RefSeq jianshuzhao$ bindash-clang dist --nthreads=8 --outfname=test.dist.txt test.bindash ref_ncbi_all_bindash.sketch 
Running bindash commit 78e0d46-dirty (2 files changed, 2 insertions(+), 1 deletion(-))
Max number of genome comparions per cached data: 2048x1024
Program ran for 891 CPU seconds and 142 real seconds.
Jianshus-MBP-2:NCBI_RefSeq jianshuzhao$ bindash-gcc dist --nthreads=8 --outfname=test.dist.txt test.bindash ref_ncbi_all_bindash.sketch 
Running bindash-gcc commit 78e0d46-clean
Max number of genome comparions per cached data: 2048x1024
Program ran for 167 CPU seconds and 36 real seconds.

With GCC 11 on MacOS, I do not have this problem even using GCC compiler, there should be something changed for GCC 13, a little bit strange for GCC on MacOS.


Thanks,

Jianshu
