### ISSUE TITLE
amino acid processing

### ISSUE THREAD

**Issue by jianshu93** [zhaoxiaofei/bindash#9]
Hello Xiaofei,

Is it possible to also provide amino acid processing like in Mash (-a option) to process 20 amino acid alphabets, instead of 4 nt.

Thanks,

Jianshu

**Comment by zhaoxiaofei** [comment]
Hi @jianshu93 

Sorry for replying so late. My mailbox was full and I did not receive email notification about this issue on github. 
You can reduce k-mer size by about 50% for amino acid sequences as compared with nculeotide sequences. 
The remaining steps are the same for both amino acid sequences and nucleotide sequences.
